#!/bin/bash

# create_cam_gif <model> <character> <npz_file>
function create_cam_gif() {
    final_gif_name="../data_dir/cam_output/$1/$2/$3/$2_$3.gif"
    mkdir -p ../data_dir/cam_output/$1/$2/$3
    CUDA_VISIBLE_DEVICES='' DISPLAY=:2 python cam_animation.py --weight-directory ../data_dir/weights/$1 --data-directory ../data_dir/simpsons_dataset --image-path ../data_dir/simpsons_dataset/$2/$3 --cam-path ../data_dir/cam_output/$1/$2/$3 --weight-limit 100
    convert -delay 30  -size 256x256 ../data_dir/cam_output/$1/$2/$3/*.png -loop 0 $final_gif_name
}

max_jobs=5

if [[ $# == 3 ]]; then
    create_cam_gif $@
elif [[ $# == 2 ]]; then
    for file in ../data_dir/simpsons_dataset/$2/*.npz
    do
        if [[ -f $file ]]; then
            while [ $(jobs | wc -l) -ge $max_jobs ]; do sleep 1; done
            create_cam_gif $@ $(basename $file) &
        fi
    done
else
    echo "./generate_cam_gifs <model> <character> <npz_file>"
fi
